### ISSUE TITLE
Update Tilix download method

### ISSUE THREAD

**Issue by CoolHandSquid** [CoolHandSquid/TireFire#18]

**Comment by CoolHandSquid** [comment]
There is no logic to stop tilix from downloading the zip twice.

**Comment by QUzAR22** [comment]
[Build.txt](https://github.com/CoolHandSquid/TireFire/files/11343957/Build.txt) 

I added tilix to the apt get command in installing necessary tools and removed the test and wget command for tilix while keeping the configuration the same. I renamed "installing tilix" to "Configuring tilix"

**Comment by CoolHandSquid** [comment]
Editing the issue for clarity:
Tilix was previously not in the Kali Rolling Repo, so it was downloaded via wget and installed that way. Due to an increase in popularity it can now easily be managed via apt. Tilix should be managed via apt as opposed to wget.

**Comment by CoolHandSquid** [comment]
I saw your PR and accepted it. Thank you for your contribution!
