### ISSUE TITLE
Typo in DNS Zone Transfer

### ISSUE THREAD

**Issue by jonathanbheadley** [CoolHandSquid/TireFire#29]
When trying to do a Zone Transfer (Main Table > DNS (8) > Zone Transfer (3)) one of the commands has a typo:
dig axfr @10.0.0.4 && dix axfr @10.0.0.4 yee.wtf && fierce -dns yee.wtf

`dix` 

![image](https://user-images.githubusercontent.com/65432843/230057481-564eaf91-cc1e-4e43-92b0-1f3066d83f27.png)

Also, -dns yee.wtf is in an invalid argument for `fierce`

![image](https://user-images.githubusercontent.com/65432843/230058049-805d9108-d761-4780-9127-fc1ac1f25580.png)

This seemed to work for me, but not sure it is what you intended:
`dig axfr @10.0.0.4 && dig axfr @10.0.0.4 yee.wtf && fierce --dns-servers 10.0.0.4 --domain yee.wtf `

**Comment by CoolHandSquid** [comment]
Thank you for the insight! I remedied both of the typos (bad syntaxes) in the HackTricks database, and they should be populated into the TireFire Database by Monday mid-morning.

**Comment by CoolHandSquid** [comment]
My PR to HackTricks (where TireFire populates it's database) has not been reviewed/accepted yet. I expect that it will be accepted in the next week. TireFire parses HackTricks weekly to updated it's database on Monday mornings, so I expect that this typo will be fixed by then.

**Comment by CoolHandSquid** [comment]
Database Update. Closing Ticket.
