### ISSUE TITLE
Display menu wraps poorly when terminal is too small

### ISSUE THREAD

**Issue by nullidy** [CoolHandSquid/TireFire#5]
Implement a wrapping functionality when terminal column size is too small to display horizontally change to vertical menu display. 

Also implementing a minumum terminal size will alleviate any other unforeseen formatting issues.

Example:
<img width="647" alt="Screen Shot 2021-10-20 at 10 51 14 AM" src="https://user-images.githubusercontent.com/40326565/138117040-85186a0b-daa2-42b9-afb4-9ca7d5347701.png">

**Comment by CoolHandSquid** [comment]
Fix implemented.
